Topics / folders may include
- python basics
- plotnine + visualization
- creating + selecting columns
- writing functions
- group + summarize data
- working with tables / joins
- tidy data
- data types
- EDA | stats
- quarto