project:
  type: website

website:
  title: "pinr resources"
  navbar:
    background: "#FF851B"
    left:
      - href: index.qmd
        text: Home
  sidebar:
    contents:
      - index.qmd
      - auto: "*.qmd"

format:
  html:
    theme: zephyr
    toc: true
